version: '3.4'

services:
  ciclo4microsale:
    image: ciclo4microsalemedallo
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:8084
  mongo:
    container_name: mongosalesmedallo
    image: mongo
    ports:
      - "27019:27017"
