version: "3.8"

services:
  app:
    container_name: micro_product
    restart: always
    build: .
    ports:
      - "3001:8080"
    links:
        - mongo
    volumes:
      - .:/CICLO4_MICRO_PRODUCT
  # mongo:
  #   container_name: mymongodb
  #   image: mongo
  #   ports:
  #     - "27018:27017"