version: '3.4'

services:
  ciclo4backend:
    image: ciclo4backendproduct
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:8080
  mongo:
    container_name: mongoproducts
    image: mongo
    ports:
      - "27021:27017"