version: '3.4'

services:
  ciclo4microcliente:
    image: ciclo4microcliente
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3003:8082
  mongo:
    container_name: mongoclients
    image: mongo
    ports:
      - "27023:27017"