version: "3.8"

services:
  app:
    container_name: micro_client
    restart: always
    build: .
    ports:
      - "3002:8080"
    links:
        - mongo
    volumes:
      - .:/CICLO4_MICRO_CLIENT
  mongo:
    container_name: mymongodb
    image: mongo
    ports:
      - "27018:27017"