version: '3.4'

services:
  ciclo4microsale:
    image: ciclo4microsale
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:8084
  mongo:
    container_name: mongosalesbogota
    image: mongo
    ports:
      - "27020:27017"
